name = "MannKendall"
uuid = "2ea28b1c-538b-46b7-9a18-2a3e9f3f1d0c"
authors = ["Michael Stamatis <email@email.com> "]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
StatsFuns = "0.9"
julia = "1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6"
